### PR TITLE
MERGE BASIC PRISMA SETUP:

### PR DESCRIPTION
**Pull request by Elena-Lou**
Basic Prisma config with an index.ts file as an example of Prisma commands.

database.sql initialises the database at build

### CODE REVIEW

**Comment by Keeghaan** [comment]
Thank you <3

**Review by apayetRun — APPROVED** [review]
Thx for the job !

**Review by nicolkaver — APPROVED** [review]
Thank you for your work :))

**Review by Keeghaan — APPROVED** [review]
I thought I already approved ^^' Sorry, thank you :*

**Pull request merged**
